### ISSUE TITLE
[bug] 15.x compatibility issue

### ISSUE THREAD

**Issue by cevin** [xuejiazhi/pgii#27]
<img width="890" alt="image" src="https://github.com/xuejiazhi/pgii/assets/338110/2befb508-5b31-476a-ab10-c8b31e790fc6">

**Comment by xuejiazhi** [comment]
The local test is as follows.
![image](https://github.com/xuejiazhi/pgii/assets/16795993/722eb04f-092c-4d21-b0ce-d4d84bc9745f)
github  fix by  86d2442
![image](https://github.com/xuejiazhi/pgii/assets/16795993/2c6eb2bc-eb64-454b-99a8-6828d0f93f6a)

**Comment by xuejiazhi** [comment]
Thank you very much

**Comment by xuejiazhi** [comment]
"use database"  have The same problem

![image](https://github.com/xuejiazhi/pgii/assets/16795993/de201b14-8044-454d-bf6a-b32e3aa8ccc7)
fix by  32d3e86
![image](https://github.com/xuejiazhi/pgii/assets/16795993/5c46f81c-e910-4d04-9ef5-16480af9d6c9)
